### ISSUE TITLE
Need docs/quickstart to launch the application

### ISSUE THREAD

**Issue by Amrithnath** [sivansundar/PokeBolt#1]
Can we have some docs on how to start contributing to this project/how to launch application? Maybe common knowledge but would love to contribute (new toKotlin)

I can help with docs if needed.

**Comment by sivansundar** [comment]
I would love to write contribution guidelines for this but this project was made as a part of an assignment. Therefore I don't think this can be an ideal opensource project to look at.  However, I do have plans of making a bunch of sample apps for opensource references and contributions so do watch the space. 

Closing this issue.
